<?php

/**
 * @file
 * Contains gcse.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gcse_help($route_name, RouteMatchInterface $route_match) {
	switch ($route_name) {
		// Main module help for the gcse module.
		case 'help.page.gcse':
			$output = '';
			$output .= '<h3>' . t('About') . '</h3>';
			$output .= '<p>' . t('Google Custom Search') . '</p>';
			return $output;
	}
}